// <auto-generated />
using System;
using HelixScheduler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelixScheduler.Infrastructure.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    partial class SchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.BusyEventResources", b =>
                {
                    b.Property<long>("BusyEventId")
                        .HasColumnType("bigint");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("BusyEventId", "ResourceId");

                    b.HasIndex("ResourceId", "BusyEventId");

                    b.ToTable("BusyEventResources", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.BusyEvents", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc", "EndUtc");

                    b.ToTable("BusyEvents", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.DemoScenarioStates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaseDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeedVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DemoScenarioStates", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ResourceProperties", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourcePropertyLinks", b =>
                {
                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("ResourceId", "PropertyId");

                    b.HasIndex("PropertyId", "ResourceId");

                    b.ToTable("ResourcePropertyLinks", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceRelations", b =>
                {
                    b.Property<int>("ParentResourceId")
                        .HasColumnType("int");

                    b.Property<int>("ChildResourceId")
                        .HasColumnType("int");

                    b.Property<string>("RelationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParentResourceId", "ChildResourceId", "RelationType");

                    b.HasIndex("ChildResourceId");

                    b.ToTable("ResourceRelations", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceTypeProperties", b =>
                {
                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("ResourceTypeId", "PropertyDefinitionId");

                    b.HasIndex("PropertyDefinitionId", "ResourceTypeId");

                    b.ToTable("ResourceTypeProperties", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.ToTable("ResourceTypes", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.Resources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSchedulable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("IsSchedulable");

                    b.HasIndex("TypeId");

                    b.ToTable("Resources", null, t =>
                        {
                            t.HasCheckConstraint("CK_Resources_Capacity", "[Capacity] >= 1");
                        });
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.RuleResources", b =>
                {
                    b.Property<long>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("RuleId", "ResourceId");

                    b.HasIndex("ResourceId", "RuleId");

                    b.ToTable("RuleResources", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.Rules", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DaysOfWeekMask")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("FromDateUtc")
                        .HasColumnType("date");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsExclude")
                        .HasColumnType("bit");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("SingleDateUtc")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly?>("ToDateUtc")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FromDateUtc", "ToDateUtc", "SingleDateUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("FromDateUtc", "ToDateUtc", "SingleDateUtc"), new[] { "IsExclude" });

                    b.ToTable("Rules", (string)null);
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.BusyEventResources", b =>
                {
                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.BusyEvents", "BusyEvent")
                        .WithMany("BusyEventResources")
                        .HasForeignKey("BusyEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.Resources", "Resource")
                        .WithMany("BusyEventResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusyEvent");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceProperties", b =>
                {
                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.ResourceProperties", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourcePropertyLinks", b =>
                {
                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.ResourceProperties", "Property")
                        .WithMany("PropertyLinks")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.Resources", "Resource")
                        .WithMany("PropertyLinks")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceRelations", b =>
                {
                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.Resources", "ChildResource")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ChildResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.Resources", "ParentResource")
                        .WithMany("ParentRelations")
                        .HasForeignKey("ParentResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildResource");

                    b.Navigation("ParentResource");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceTypeProperties", b =>
                {
                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.ResourceProperties", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.ResourceTypes", "ResourceType")
                        .WithMany("ResourceTypeProperties")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyDefinition");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.Resources", b =>
                {
                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.ResourceTypes", "Type")
                        .WithMany("Resources")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.RuleResources", b =>
                {
                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.Resources", "Resource")
                        .WithMany("RuleResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelixScheduler.Infrastructure.Persistence.Entities.Rules", "Rule")
                        .WithMany("RuleResources")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.BusyEvents", b =>
                {
                    b.Navigation("BusyEventResources");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceProperties", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("PropertyLinks");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.ResourceTypes", b =>
                {
                    b.Navigation("ResourceTypeProperties");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.Resources", b =>
                {
                    b.Navigation("BusyEventResources");

                    b.Navigation("ChildRelations");

                    b.Navigation("ParentRelations");

                    b.Navigation("PropertyLinks");

                    b.Navigation("RuleResources");
                });

            modelBuilder.Entity("HelixScheduler.Infrastructure.Persistence.Entities.Rules", b =>
                {
                    b.Navigation("RuleResources");
                });
#pragma warning restore 612, 618
        }
    }
}
